services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nextcloud-data:/var/www/html
    networks:
      - ecosystem
    environment:
      - NEXTCLOUD_ADMIN_USER=nextadmin
      - NEXTCLOUD_ADMIN_PASSWORD=nextadmin